# Generated by Django 3.2.5 on 2021-07-20 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('describe_problem', models.CharField(max_length=200)),
                ('code_to_debug', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution_to_problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_note', models.CharField(max_length=200)),
                ('correct_code', models.TextField()),
                ('solution_author', models.CharField(blank=True, max_length=200, null=True)),
                ('post_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpApp.postproblem')),
            ],
        ),
    ]
