# Generated by Django 3.2.5 on 2021-07-26 09:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0002_alter_postproblem_code_to_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_to_problems',
            name='correct_code',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
